export const GET_COUNTRIES_REQUEST = 'GET_COUNTRIES_REQUEST';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_FAILED = 'GET_COUNTRIES_FAILED';

export const GET_COUNTRY_BY_NAME_REQUEST = 'GET_COUNTRY_BY_NAME_REQUEST'
export const GET_COUNTRY_BY_NAME_SUCCESS = 'GET_COUNTRY_BY_NAME_SUCCESS '
export const GET_COUNTRY_BY_NAME_FAILED = 'GET_COUNTRY_BY_NAME_FAILED'

export const GET_COUNTRIES_BY_REGION_REQUEST = 'GET_COUNTRIES_BY_REGION_REQUEST'
export const GET_COUNTRIES_BY_REGION_SUCCESS = 'GET_COUNTRIES_BY_REGION_SUCCESS'
export const GET_COUNTRIES_BY_REGION_FAILED = 'GET_COUNTRIES_BY_REGION_FAILED'

export const GET_COUNTRIES_BY_NAME_REQUEST = 'GET_COUNTRIES_BY_NAME_REQUEST'
export const GET_COUNTRIES_BY_NAME_SUCCESS = 'GET_COUNTRIES_BY_NAME_SUCCESS'
export const GET_COUNTRIES_BY_NAME_FAILED = 'GET_COUNTRIES_BY_NAME_FAILED'